package org.example.employeeapp.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity class representing an employee.
 *
 * Maps to the `employees` table in the database.
 */
@Data
@Entity
@Table(name = "employees")
public class Employee {

    /**
     * Unique identifier for the employee.
     *
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The name of the employee.
     *
     * This field is mapped to the "employee_name" column in the database.
     * The JSON property name for this field is also "employee_name".
     */
    @JsonProperty("employee_name")
    @Column(name = "employee_name")
    private String employeeName;

    /**
     * The salary of the employee.
     *
     * This field is mapped to the "employee_salary" column in the database.
     * The JSON property name for this field is also "employee_salary".
     */
    @JsonProperty("employee_salary")
    @Column(name = "employee_salary")
    private double employeeSalary;

    /**
     * The age of the employee.
     *
     * This field is mapped to the "employee_age" column in the database.
     * The JSON property name for this field is also "employee_age".
     */
    @JsonProperty("employee_age")
    @Column(name = "employee_age")
    private int employeeAge;

    /**
     * The URL of the employee's profile image.
     *
     * This field is mapped to the "profile_image" column in the database.
     * The JSON property name for this field is also "profile_image".
     */
    @JsonProperty("profile_image")
    @Column(name = "profile_image")
    private String profileImage;
}